name = "posthog-inject-sign-ta"
main = "worker.js"
compatibility_date = "2026-09-30"
account_id = "5634762de98310f403bf30445c60108b"
workers_dev = false

[[routes]]
pattern = "sign.team-abfindung.de/*"
zone_name = "team-abfindung.de"
